apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-oci-sample-app
  namespace: gne-test
spec:
  interval: 10m0s
  path: .
  prune: true
  sourceRef:
    kind: OCIRepository
    name: flux-oci-sample
  targetNamespace: gne-test